### ISSUE TITLE
Add connection group permissions

### ISSUE THREAD

**Issue by zinesa** [scicore-unibas-ch/ansible-modules-guacamole#12]
When we're creating/updating a user and want to specify an allowed_connection, and this connection belongs to a Connection group (not Root), Guacamole requires that the user also has permissions on this Connection group. One way to fix this could be to do something like this inside guacamole_update_user_permissions():
    add_group_permission = {
        'op': operation,
        'path': '/connectionGroupPermissions/<connectionGroupID>',
        'value': 'READ'
    }
    if operation == 'add':
        payload.append(add_group_permission)

**Comment by pescobar** [comment]
can you test https://github.com/scicore-unibas-ch/ansible-modules-guacamole/pull/16 ?

**Comment by zinesa** [comment]
Everything works as intended. Thanks, that was fast.

**Comment by pescobar** [comment]
closed by https://github.com/scicore-unibas-ch/ansible-modules-guacamole/pull/16

Published a new version `0.0.13` to ansible galaxy including the fix
