### ISSUE TITLE
Add Ignore server certificate option for RDP connection

### ISSUE THREAD

**Issue by zinesa** [scicore-unibas-ch/ansible-modules-guacamole#13]
We could add somethng like `rdp_ignore_cert=dict(type='bool',required=False)` to guacamole_connection module_args, and add 'ignore-cert' parameter to payload in guacamole_populate_connection_payload:
`"ignore-cert": module_params['rdp_ignore_cert']`

**Comment by pescobar** [comment]
I have created PR https://github.com/scicore-unibas-ch/ansible-modules-guacamole/pull/15 adding the new option `rdp_ignore_server_certs`. Can you test it?

**Comment by zinesa** [comment]
Yes, it works as intended, thanks.

**Comment by pescobar** [comment]
closed by https://github.com/scicore-unibas-ch/ansible-modules-guacamole/pull/15
