### ISSUE TITLE
Add a new module to handle user groups

### ISSUE THREAD

**Issue by sbraz** [scicore-unibas-ch/ansible-modules-guacamole#18]
Hi,
Could you please add a module to handle user groups? The main thing we need is the ability [to assign connections to user groups](https://github.com/ridvanaltun/guacamole-rest-api-documentation/blob/master/docs/USER-GROUPS.md#assign-connections-to-user-group).

**Comment by pescobar** [comment]
I have a WIP in https://github.com/scicore-unibas-ch/ansible-modules-guacamole/pull/14 but I don't know when I will have time to continue working on it

**Comment by sbraz** [comment]
Thanks, I didn't notice that PR :)
