### ISSUE TITLE
HTTP Status 404 – Not Found

### ISSUE THREAD

**Issue by johnmcavoy** [scicore-unibas-ch/ansible-modules-guacamole#26]
Hi there,

Im using Bitnami's latest Gucamole build but when I try and run the playbook using the Ansible module I'm getting the following error. 

    - name: Add a new console connection
      scicore.guacamole.guacamole_connection:
        base_url: http://1.2.3.4/guacamole

    "msg": "Could not obtain access token from http://192.168.128.206/guacamole/api/tokens: HTTP Error 404: "

Any suggestions?

Thanks

John

**Comment by pescobar** [comment]
I guess the `base_url` you are using is not correct. 

I would suggest to try to access the used `base_url` using your browser to verify it's working.

You can also use curl for debugging. You can find some examples [here](https://github.com/scicore-unibas-ch/ansible-modules-guacamole/blob/master/devel-utils/curl-cheatsheet.sh)

**Comment by johnmcavoy** [comment]
thanks for the reply, I rebuild from scratch and it worked fine so maybe something slightly different with the Bitnami build? Thanks for your help. 

Regards

**Comment by pescobar** [comment]
I have never tried the bitnami build. 

Glad to hear you got it working
