### ISSUE TITLE
disable account  after

### ISSUE THREAD

**Issue by Pat65** [scicore-unibas-ch/ansible-modules-guacamole#3]
Hi good job but impossible to set the attribute disable_account_after. 
no error but nothing is down

**Comment by pescobar** [comment]
can you post your ansible playbook? how are you passing the argument? 

The guacamole api expects value `disable_account_after` in format `"2020-10-23"` . Are you using this format?

**Comment by Pat65** [comment]
Hi,
my fault, i used an incorrect date format. With "YYY-MM-DD" it works

**Comment by pescobar** [comment]
Thanks for reporting this issue. I have fixed the docs and the README with the right date format. 

Check https://github.com/scicore-unibas-ch/ansible-modules-guacamole/commit/8f2dfa3b053e8f0ca703494c52dad3694872b2c2
