### ISSUE TITLE
feature request: support TOTP

### ISSUE THREAD

**Issue by alfajorcito** [scicore-unibas-ch/ansible-modules-guacamole#35]
Currently, these modules work as expected, unless you enable the [TOTP plugin](https://guacamole.apache.org/doc/gug/totp-auth.html).

If you are eventually planning on using TOTP, as of now, you can only use them during the initial Guacamole deployment - they stop working as expected once you activate the TOTP plugin (to be more precise, auth starts failing, resulting in 403 errors).

Ideally, we should be able to use all modules inside this collection after enabling TOTP as well (for example, by allowing the user to set the TOTP secret key as an additional variable)

**Comment by pescobar** [comment]
Hi @alfajorcito 

It should work if your admin account (the one used by ansible) is created in the guacamole db and you have the database extension
installed. Check this post from the guacamole developers for more details: https://www.mail-archive.com/dev@guacamole.apache.org/msg03837.html

**Comment by pescobar** [comment]
After reading again the reply from the guacamole developers, it seems it won't work when using TOPT plugin

```
There are 2FA extensions which are part of guacamole-client (the Duo and
TOTP support) which will veto the authentication result of other extensions
and enforce multi-factor. That won't happen if the multifactor auth is
happening on the OpenID side, outside of Guacamole's view.```

In this case I think the only option to use 2FA is to use OpenID+2FA instead of TOPT.  I don't know how ansible could handle the 2FA auth when TOPT plugin is enabled.

**Comment by alfajorcito** [comment]
Thank you for your prompt response!

I do have the DB extension installed, since it's a prerequisite for the TOTP plugin. Unfortunately, a switch to OpenID is not an option at the moment - but I will keep this in mind in case circumstances change.

I was hoping it would be doable somehow via the REST API, but I'm afraid I'm unable to provide any deeper insights on how exactly to achieve this 😢 If this implies that the issue should be closed, please feel free to do so ><'

**Comment by pescobar** [comment]
Based on the reply from the guacamole developers enabling TOPT plugin will enforce multi-factor auth so it wouldn't be possible to access the API using ansible in an automated way. 

If you need to enable 2FA while still having api access from ansible without 2FA you have to use an auth plugin where the multifactor auth happens outisde of guacamole's view, like openid

I am closing this ticket as I don't think it's possible to access the api with ansible when the TOTP plugin is enabled.
