### ISSUE TITLE
Add the ability to support the disabling of copy and paste in guacamole_connections

### ISSUE THREAD

**Issue by ION28** [scicore-unibas-ch/ansible-modules-guacamole#36]
I will be opening a pull request to add this functionality shortly.

More info can be found about this setting in the Guacamole docs here: https://guacamole.apache.org/doc/gug/configuring-guacamole.html#disabling-clipboard-access

My PR will default to allowing copy and paste by default, but add these as configurable options for users that want to disable these in connections

**Comment by pescobar** [comment]
fixed in new release [0.0.21](https://github.com/scicore-unibas-ch/ansible-modules-guacamole/releases/tag/0.0.21)
