### ISSUE TITLE
guacamole_user.py

### ISSUE THREAD

**Issue by Pat65** [scicore-unibas-ch/ansible-modules-guacamole#4]
Hi,
to work with other database than postgresql you have to change the lines : 
URL_UPDATE_USER = "{url}/api/session/data/postgresql/users/{username}?token={token}"  to  URL_UPDATE_USER = "{url}/api/session/data/{datasource}/users/{username}?token={token}"

URL_GET_USER_PERMISSIONS = "{url}/api/session/data/postgresql/users/{username}/permissions?token={token}"  to URL_GET_USER_PERMISSIONS = "{url}/api/session/data/{datasource}/users/{username}/permissions?token={token}" 

in file ../collections/ansible_collections/scicore/guacamole/plugins/modules/guacamole_user.py

**Comment by pescobar** [comment]
Thanks for the report. 

I am aware of this and I have applied the fix in an open PR https://github.com/scicore-unibas-ch/ansible-modules-guacamole/pull/1/commits/346fa94aa121238dd0896545585ffef267174433 but I still couldn't have the time to merge it upstream and do a new release.

If you need this I can publish a new release only with this fix

**Comment by pescobar** [comment]
I have published a new release `0.0.9` to ansible galaxy which fixes this issue.

Check https://galaxy.ansible.com/scicore/guacamole
