### ISSUE TITLE
Missing administrator console setting

### ISSUE THREAD

**Issue by LikeAPeanut** [scicore-unibas-ch/ansible-modules-guacamole#49]
Hello !

In the RDP connections setting, the administrator console setting is missing.
When we execute the code, this parameter is forced to 0 when we restart the code.
Is it possible to add a variable for this parameter?

![admconsole](https://github.com/scicore-unibas-ch/ansible-modules-guacamole/assets/167857248/a2061cab-b223-4447-8d5e-e84ce7570773)

Thanks !

**Comment by pescobar** [comment]
The project is open for contributions but I have no time to work on it. 

I have updated the [README](https://github.com/scicore-unibas-ch/ansible-modules-guacamole?tab=readme-ov-file#maintainers-wanted)
