### ISSUE TITLE
error with parent_identifier

### ISSUE THREAD

**Issue by Pat65** [scicore-unibas-ch/ansible-modules-guacamole#8]
Hi, 
since version 0.0.10 when i try to manage a user i got this error
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: guacamole_get_connections() got an unexpected keyword argument 'parent_identifier'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1604051826.34-32240-17112929908612/AnsiballZ_guacamole_user.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1604051826.34-32240-17112929908612/AnsiballZ_guacamole_user.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1604051826.34-32240-17112929908612/AnsiballZ_guacamole_user.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.scicore.guacamole.plugins.modules.guacamole_user', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_scicore.guacamole.guacamole_user_payload_yV4Kr9/ansible_scicore.guacamole.guacamole_user_payload.zip/ansible_collections/scicore/guacamole/plugins/modules/guacamole_user.py\", line 557, in <module>\n  File \"/tmp/ansible_scicore.guacamole.guacamole_user_payload_yV4Kr9/ansible_scicore.guacamole.guacamole_user_payload.zip/ansible_collections/scicore/guacamole/plugins/modules/guacamole_user.py\", line 452, in main\nTypeError: guacamole_get_connections() got an unexpected keyword argument 'parent_identifier'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

The playbook
 tasks:
    - name: Deactivate guacamole user
      scicore.guacamole.guacamole_user:
        base_url: http://guacamole-dev.di.unistra.fr:8080/guacamole
        auth_username: "{{ admin_cpt }}"
        auth_password: "{{ admin_pwd }}"
        username: "{{ compte }}"
        disabled: yes
        allowed_connections:
          - dummy_connection
      when: aktion == "désactiver"
    - name: Activate guacamole user
      scicore.guacamole.guacamole_user:
        base_url: http://guacamole-dev.di.unistra.fr:8080/guacamole
        auth_username: "{{ admin_cpt }}"
        auth_password: "{{ admin_pwd }}"
        username: "{{ compte }}"
        disabled: no
        disable_account_after: "{{disable_after}}"
        allowed_connections:
          - dummy_connection
      when: aktion == "activer"

**Comment by pescobar** [comment]
I have published a new version `0.0.11` that should fix this problem. Let me know if it works for you

**Comment by Pat65** [comment]
Hi,
every thing works now
Thanks
